### PR TITLE
[Middleware_01] Built Processor Classes

### LINKED ISSUE #69: [Middleware_01] Build and Test Middleware_01 Production Classes
**What is the use case? Please describe.**
For this sprint task, you'll be building and testing all of the classes in the `edu.oakland.production.middleware02` package. 

**Sprint Task Setup**

To be done by @brendam19 , @juliawang2014 , or @martinhughes0722 before the rest of the team starts working on it:

1. Edit this issue message to add a checkbox for each class, and assign it to the correct team member from #58 .

**Prerequisites**

Please makes sure that your test plan from #58 for the class you are writing is closed and merged to main before starting this, to ensure that all of the documentation you need for this is in the correct spot.

**Steps**

To be done by each team member for each class they are developing a test plan for:

1. Each team member should watch the last ~18 minutes of @andrewdimmer 's [Test Driven Development Crash Course](https://youtu.be/eSc0aY4GhPs)
2. One person should create a branch off of main called `define-Name_Of_Class` (ex. the `Demo` classes and tests get build on a branch called `build-Demo`). Everyone else in the programming pair or group should then checkout that branch.
3. Using the information in the video, use test driven development to build all the required classes, stubs, and tests. Remember: you've already defined what you need to build at https://github.com/andrewdimmer/csi-3370-software-project/tree/main/docs/uml-class-diagrams/middleware01 !
4. Commit your changes with the message `[Middleware_01] Built Name_Of_Class`
5. Push your changes
6. Create a pull request with the name `[Middleware_01] Built Name_Of_Class` and the rest of the information like description, tags, etc. For reference, the settings on the right hand side should match this issue, with the exception that the assignees on the PR are just those who are pushing code.
7. Once your code is complete, add @andrewdimmer as a reviewer.

**Tasks to Complete**

- [x] Allocate Team Members to Classes - @brendam19 , @juliawang2014 , or @martinhughes0722
- [x] Build MiddlewareGisInterfaceImplementation - @GitHubUsername1
- [x] Build MiddlewareGisProcessorImplementation - @githubusername2
- [x] Build MiddlewareGisManagerImplementation - @GithubUsername3

**Additional context**
Note: if for some reason you need to change a public interface or shared data type, reach out to @andrewdimmer who can help you manage making that BREAKING CHANGE.

Note: if you run into merge conflicts, let @andrewdimmer know and he can help you resolve them.

### PR DESCRIPTION
**Pull request by jvalentini555**
Fixes #69

### CODE REVIEW

**Review by brendam19 — APPROVED** [review]

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisManagerStub.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+  public void storeLocationDataPoint() {
+    
+  }
+    
+  public String attemptToRegainGpsLock(String satelliteName) {
+    return "";
+  }
+    
+  public String evaluateGpsSignalStrength(Satellite satellite) {
+    return "GPS0";
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisManagerStub.java]: This shouldn't be hard coded, but should instead be used to verify that basically the correct satellite was sent in. (Basically the same as how you do it above.)
```suggestion
    return satellite.getSatelliteName();
```

**Review by andrewdimmer — CHANGES_REQUESTED** [review]
One minor fix then you're all set to merge!

**Review by andrewdimmer — APPROVED** [review]
Looks good to me, you are all set to merge!
