### PR TITLE
[Middleware_01] Built MiddlewareGisInterface Tests and Implementation

### LINKED ISSUE #69: [Middleware_01] Build and Test Middleware_01 Production Classes
**What is the use case? Please describe.**
For this sprint task, you'll be building and testing all of the classes in the `edu.oakland.production.middleware02` package. 

**Sprint Task Setup**

To be done by @brendam19 , @juliawang2014 , or @martinhughes0722 before the rest of the team starts working on it:

1. Edit this issue message to add a checkbox for each class, and assign it to the correct team member from #58 .

**Prerequisites**

Please makes sure that your test plan from #58 for the class you are writing is closed and merged to main before starting this, to ensure that all of the documentation you need for this is in the correct spot.

**Steps**

To be done by each team member for each class they are developing a test plan for:

1. Each team member should watch the last ~18 minutes of @andrewdimmer 's [Test Driven Development Crash Course](https://youtu.be/eSc0aY4GhPs)
2. One person should create a branch off of main called `define-Name_Of_Class` (ex. the `Demo` classes and tests get build on a branch called `build-Demo`). Everyone else in the programming pair or group should then checkout that branch.
3. Using the information in the video, use test driven development to build all the required classes, stubs, and tests. Remember: you've already defined what you need to build at https://github.com/andrewdimmer/csi-3370-software-project/tree/main/docs/uml-class-diagrams/middleware01 !
4. Commit your changes with the message `[Middleware_01] Built Name_Of_Class`
5. Push your changes
6. Create a pull request with the name `[Middleware_01] Built Name_Of_Class` and the rest of the information like description, tags, etc. For reference, the settings on the right hand side should match this issue, with the exception that the assignees on the PR are just those who are pushing code.
7. Once your code is complete, add @andrewdimmer as a reviewer.

**Tasks to Complete**

- [x] Allocate Team Members to Classes - @brendam19 , @juliawang2014 , or @martinhughes0722
- [x] Build MiddlewareGisInterfaceImplementation - @GitHubUsername1
- [x] Build MiddlewareGisProcessorImplementation - @githubusername2
- [x] Build MiddlewareGisManagerImplementation - @GithubUsername3

**Additional context**
Note: if for some reason you need to change a public interface or shared data type, reach out to @andrewdimmer who can help you manage making that BREAKING CHANGE.

Note: if you run into merge conflicts, let @andrewdimmer know and he can help you resolve them.

### PR DESCRIPTION
**Pull request by jvalentini555**
Fixes #69

### CODE REVIEW

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+import edu.oakland.production.middleware01.MiddlewareGisProcessor;
+import edu.oakland.test.middleware01.MiddlewareGisProcessorStub;
+import edu.oakland.production.middleware01.MiddlewareGisInterface;
+import edu.oakland.production.middleware01.MiddlewareGisInterfaceImplementation;
+
+import edu.oakland.helper.admin.Satellite;
+import java.lang.IllegalArgumentException;
+import edu.oakland.helper.admin.LocationDataPoint;
+
+@DisplayName("Middleware GIS interface test")
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java]: Really minor nitpick, but I recommend calling it this so that the logs are consistent across all teams.
```suggestion
@DisplayName("MiddlewareGisInterfaceImplementation Unit Tests")
```

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+public class MiddlewareGisInterfaceImplementationTests {
+    
+  @Test
+  @DisplayName("Signal received from Display")
+  void isGpsSignalStrengthReceived() {
+
+  }
+
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java]: If this test is no longer required, feel free to delete it!
```suggestion
  @Test
  @DisplayName("Signal received from Display")
  void isGpsSignalStrengthReceived() {

  }

```

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+  @Test
+  @DisplayName("Signal pass successful from interface to Display")
+
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java]: Just cleaning up some extra white space... :)
```suggestion
```

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+  void passSignalStrengthUc1() {
+    Satellite satellite = new Satellite();
+
+    MiddlewareGisInterface gisInterface = new MiddlewareGisInterfaceImplementation(new MiddlewareGisProcessorStub());
+    assertEquals(satellite.getSatelliteName(), gisInterface.receiveGpsSignalStrengthUc1(satellite));
+
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java]: Just cleaning up some extra white space... :)
```suggestion
```

File: docs/uml-class-diagrams/middleware01/test/MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests.puml [hunk 5]
```diff
@@ -1,9 +1,11 @@
 @startuml MiddlewareGisProcessorImplementationTests
 
 package edu.oakland.test.middleware01 {
-    class MiddlewareGisProcessorImplementationTests {
-
-    }
+  class MiddlewareGisProcessorImplementationTests {
+    + void isGpsSignalStrengthNull()
+    + void checkValueGpsSignalStrength()
```
Comment (andrewdimmer) [inline docs/uml-class-diagrams/middleware01/test/MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests.puml]: Just updating the test plan document to match what was implemented.
```suggestion
    + void passSignalStrengthUc1()
    + void passSignalStrengthUc2()
```

File: docs/uml-class-diagrams/middleware01/test/MiddlewareGisManagerImplementationTests/MiddlewareGisManagerImplementationTests.puml [hunk 6]
```diff
@@ -1,9 +1,22 @@
 @startuml MiddlewareGisManagerImplementationTests
```
Comment (andrewdimmer) [inline docs/uml-class-diagrams/middleware01/test/MiddlewareGisManagerImplementationTests/MiddlewareGisManagerImplementationTests.puml]: No action required, this test plan looks good, and if it's not already merged feel free to do so. Just for the future though, you may want to make sure that you pull `main` before creating a new branch, and make sure you switch to a new, clean branch after each PR.

File: docs/uml-class-diagrams/middleware01/test/MiddlewareGisInterfaceImplementationTests/MiddlewareGisInterfaceImplementationTests.puml [hunk 7]
```diff
@@ -1,9 +1,11 @@
 @startuml MiddlewareGisInterfaceImplementationTests
```
Comment (andrewdimmer) [inline docs/uml-class-diagrams/middleware01/test/MiddlewareGisInterfaceImplementationTests/MiddlewareGisInterfaceImplementationTests.puml]: No action required, this test plan looks good, and if it's not already merged feel free to do so. Just for the future though, you may want to make sure that you pull main before creating a new branch, and make sure you switch to a new, clean branch after each PR.

**Review by andrewdimmer — CHANGES_REQUESTED** [review]
This looks great! A few minor formatting and naming changes, but otherwise this looks perfect to me, and you should be set to merge it once that's all set!

File: docs/uml-class-diagrams/middleware01/test/MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests.puml (hunk 5 above)
Comment (jvalentini555) [reply docs/uml-class-diagrams/middleware01/test/MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests.puml]: Isn't what you commented on for the the Processor? We had the Uc1 and Uc2 confusion in the Interface. Though I will change the interface document. @andrewdimmer

**Review by brendanfraser597 — APPROVED** [review]

**Review by brendam19 — APPROVED** [review]

File: src/main/java/edu/oakland/production/middleware01/MiddlewareGisInterfaceImplementation.java [hunk 8]
```diff
@@ -0,0 +1,45 @@
+package edu.oakland.production.middleware01;
+
+import edu.oakland.helper.admin.Satellite;
+import edu.oakland.production.middleware01.MiddlewareGisInterface;
```
Comment (andrewdimmer) [inline src/main/java/edu/oakland/production/middleware01/MiddlewareGisInterfaceImplementation.java:4]: While it's building without it being required, I'd feel better if we imported the `MiddlewareGisProcessor` here as well.
```suggestion
import edu.oakland.production.middleware01.MiddlewareGisInterface;
import edu.oakland.production.middleware01.MiddlewareGisProcessor;
```

File: src/main/java/edu/oakland/production/middleware01/MiddlewareGisInterfaceImplementation.java [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+   * Creates a MiddlewareGisInterfaceImplementation to receive the Satellite signal.
+   *
+   * @param middlewareGisProcessor  The class that this class will pass the Satellite signal to.
+   *
+   */
+  public MiddlewareGisInterfaceImplementation(MiddlewareGisProcessor middlewareGisProcessor) {
+    this.middlewareGisProcessor = middlewareGisProcessor;
+    if (this.middlewareGisProcessor == null) {
+      throw new IllegalArgumentException("processor cannot be null");
+    }
```
Comment (andrewdimmer) [inline src/main/java/edu/oakland/production/middleware01/MiddlewareGisInterfaceImplementation.java]: This is fine if you want to leave it, but generally you want to validate the argument coming in, then only set the attribute if it passes validation. If you want to use that design pattern, it would be like this:
```suggestion
    if (middlewareGisProcessor == null) {
      throw new IllegalArgumentException("processor cannot be null");
    }
    this.middlewareGisProcessor = middlewareGisProcessor;
```

File: src/main/java/edu/oakland/production/middleware01/MiddlewareGisInterfaceImplementation.java [hunk 10]
```diff
@@ -0,0 +1,45 @@
+package edu.oakland.production.middleware01;
+
+import edu.oakland.helper.admin.Satellite;
+import edu.oakland.production.middleware01.MiddlewareGisInterface;
+
+/**
+ * This class shall recieve that GPS signal from display and pass it to GIS processor.
+ *
+ */
+
```
Comment (andrewdimmer) [inline src/main/java/edu/oakland/production/middleware01/MiddlewareGisInterfaceImplementation.java]: Generally you don't want any space between the Javadoc and what it describes, as some IDEs view it differently if there is a space there.
```suggestion
```

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+import org.junit.jupiter.api.DisplayName;
+import org.junit.jupiter.api.Test;
+
+@DisplayName("MiddlewareGisInterfaceImplementation Unit Tests")
+public class MiddlewareGisInterfaceImplementationTests {
+
+  @Test
+  @DisplayName("Signal pass successful from interface to Display")
+  void passSignalStrengthUc1() {
+    Satellite sat = new Satellite("GPS0", 5);
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java:22]: Generally we don't want to hard code values for testing, and instead want to generate random cases, but this if fine for what you're doing because it is a pass through.

File: src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+    MiddlewareGisProcessor stub = new MiddlewareGisProcessorStub();
+    MiddlewareGisInterface gisInterface = new MiddlewareGisInterfaceImplementation(stub);
+    assertEquals(sat.getSatelliteName(), gisInterface.receiveGpsSignalStrengthUc1(sat));
+  }
+
+  @Test
+  @DisplayName("Signal pass successful from interface to Display")
+  void passSignalStrengthUc2() {
+    Satellite sat = new Satellite("GPS0", 5);
```
Comment (andrewdimmer) [inline src/test/java/edu/oakland/test/middleware01/MiddlewareGisInterfaceImplementationTests.java:31]: Generally we don't want to hard code values for testing, and instead want to generate random cases, but this if fine for what you're doing because it is a pass through.

**Review by andrewdimmer — CHANGES_REQUESTED** [review]
Couple really, really tiny changes, then you're set to merge!

**Review by andrewdimmer — APPROVED** [review]
You are all set to merge! Well done!
